---
k3s_version: v1.23.5+k3s1
# image tag for kube-vip
kube_vip_tag_version: "v0.4.4"

# this is the user that has ssh access to these machines
ansible_user: core
systemd_dir: /etc/systemd/system
ansible_python_interpreter: "/home/core/.opt/pypy/bin/python"
python_version: '3.9'
pypy_version: '7.3.8'

# Set your timezone
system_timezone: "Your/Timezone"

# interface which will be used for flannel
vip_iface: "eth0"

# apiserver_endpoint is virtual ip-address which will be configured on each master
apiserver_endpoint: "xxx.xxx.xxx.xxx"

# Where to place the k3s binaries
binary_path: "/opt/bin"

# k3s_token is required  masters can talk together securely
# this token should be alpha numeric only
k3s_token: "some-SUPER-DEDEUPER-secret-password"

# change these to your liking, the only required one is--no-deploy servicelb
extra_server_args: "--flannel-backend=none --no-deploy servicelb --no-deploy traefik"
extra_agent_args: ""
