---
- name: Set same timezone on every Server
  timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

# Flatcar does include SELinux but does not enforce it by default so this is not really necessary, also ansible SELinux module is a hassle
# - name: Set SELinux to disabled state
#   selinux:
#     state: disabled
#   # when: ansible_os_family == "RedHat"

- name: Enable IPv4 forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Add br_netfilter to /etc/modules-load.d/
  copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="
  # when: ansible_os_family == "RedHat"

- name: Load br_netfilter
  modprobe:
    name: br_netfilter
    state: present
  # when: ansible_os_family == "RedHat"

- name: Set bridge-nf-call-iptables (just to be sure)
  sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  # when: ansible_os_family == "RedHat"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Disable docker socket
  systemd:
    name: docker.socket
    enabled: no
    state: stopped
  failed_when: false
- name: Disable docker daemon
  systemd:
    name: docker.service
    enabled: no
    state: stopped
  failed_when: false
  # k3s uses its own containerd so this service is unnecessary
- name: Disable containerd
  systemd:
    name: containerd
    enabled: no
    state: stopped
  failed_when: false