---
- name: Copy K3s service file
  template:
    src: "k3s.service.j2"
    dest: "{{ systemd_dir }}/k3s-node.service"
    owner: root
    group: root
    mode: 0755
  register: add_service

- name: Enable and check K3s service
  systemd:
    name: k3s-node
    daemon_reload: yes
    state: restarted
    enabled: yes
  when: add_service.changed or not installed
- name: Mark node as installed
  file:
    path: /etc/rancher/.ansible-installed
    state: touch
